#!/bin/bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=bottom height=32 color=$background padding_left=16 padding_right=16

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=4
  padding_right=4
  label.font="Iosevka Nerd Font:Bold:13.0"
  icon.font="Iosevka Nerd Font:Bold:13.0"

  icon.color=$foreground
  label.color=$foreground
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

# SPACE_ICONS=("I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X")
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid="$(($i+1))"
#   space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]}"
#     icon.font="Iosevka Nerd Font:Bold:14.0"
#     icon.padding_left=4
#     icon.padding_right=4
#     background.color=0x40ffffff
#     background.corner_radius=0
#     background.height=25
#     label.drawing=off
#     script="$PLUGIN_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done

#!/bin/bash

SPACE_SIDS=(1 2 3 4 5 6 7 8 9 10)
SPACE_ICONS=("" "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X")

for sid in "${SPACE_SIDS[@]}"; do
  sketchybar --add space space.$sid left                                      \
             --set space.$sid space=$sid                                      \
                               icon=${SPACE_ICONS[$sid]}                       \
                               icon.font="Iosevka Nerd Font:Bold:12.0"         \
                               icon.width=32                                   \
                               icon.align=center                               \
                               label.drawing=off                               \
                               icon.padding_left=6                             \
                               icon.padding_right=6                            \
                               padding_left=2                                  \
                               padding_right=2                                 \
                               background.drawing=off                          \
                               background.height=18                            \
                               background.corner_radius=5                      \
                               background.color=0x228ABEB7                     \
                               background.border_color=0x448ABEB7              \
                               background.border_width=1                       \
                               click_script="yabai -m space --focus $sid"      \
                               script="$PLUGIN_DIR/space.sh"
done


sketchybar --add item space_separator left                               \
           --set space_separator icon=""                                 \
                                 label.drawing=off                       \
                                 background.drawing=off                  \
                                 script="$PLUGIN_DIR/space_windows.sh"   \
           --subscribe space_separator space_windows_change
#


##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

#!/usr/bin/env bash

stat=(
  background.drawing=off
  label.font="Iosevka Nerd Font:Bold:13.0"
  label.color=0xffc0caf5
  icon.font="Iosevka Nerd Font:Regular:15.0"
  icon.padding_left=8
  icon.padding_right=4
  label.padding_left=0
  label.padding_right=8
  padding_left=0
  padding_right=0
)

sketchybar --add item network_down right \
           --set network_down "${stat[@]}" \
                               update_freq=3 \
                               icon="󰛴" \
                               icon.color=0xff7aa2f7 \
                               label="--" \
                               script="$PLUGIN_DIR/network.sh"

sketchybar --add item network_up right \
           --set network_up "${stat[@]}" \
                             icon="󰛶" \
                             icon.color=0xff9ece6a \
                             label="--"

sketchybar --add item net_sep right \
           --set net_sep icon="│" \
                          icon.font="Iosevka Nerd Font:Regular:12.0" \
                          icon.color=0xff3b4261 \
                          icon.padding_left=4 \
                          icon.padding_right=4 \
                          label.drawing=off \
                          background.drawing=off \
                          padding_left=0 \
                          padding_right=0

sketchybar --add item memory right \
           --set memory "${stat[@]}" \
                         update_freq=5 \
                         icon="󰍛" \
                         icon.color=0xff7aa2f7 \
                         script="$PLUGIN_DIR/memory.sh"

sketchybar --add item disk right \
           --set disk "${stat[@]}" \
                       update_freq=60 \
                       icon="󰋊" \
                       icon.color=0xffbb9af7 \
                       script="$PLUGIN_DIR/disk.sh"

sketchybar --add item cpu right \
           --set cpu "${stat[@]}" \
                      update_freq=5 \
                      icon="󰻠" \
                      icon.color=0xff9ece6a \
                      script="$PLUGIN_DIR/cpu.sh"


sketchybar --add item front_app center \
           --set front_app icon.drawing=off \
                            label="" \
                            label.font="Iosevka Nerd Font:Bold:13.0" \
                            label.color=0xffc0caf5 \
                            label.padding_left=8 \
                            label.padding_right=8 \
                            padding_left=3 \
                            padding_right=3 \
                            background.drawing=on \
                            background.height=22 \
                            background.corner_radius=7 \
                            background.color=0x223b4261 \
                            script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
