#! /bin/bash

# 多显示屏配置
m1="eDP-1"
name="HDMI-1-0"

both="0"

if [ "$(xrandr | grep " connected " | grep $name)" ]; then
	xrandr --output $name --rate 74.99 --mode 2560x1080
	bspc monitor $name -d I II III IV V VI VII VII IX X

	if [ $both == '0' ]; then
		xrandr --output $m1 --off
		bspc monitor $m1 -r
	else	
		xrandr --output $m1 --rate 60.10 --mode 1920x1080
		bspc monitor $m1 -d -
		xrandr --output $name --primary --output $m1 --left-of $name
	fi


else
	xrandr --output $m1 --rate 60.10 --mode 1920x1080
	bspc monitor $name -r
	bspc monitor $m1 -d I II III IV V VI VII VII IX X
fi

# xrandr --output eDP-1 --rate 60.10 --mode 1920x1080

#in/env XSECURELOCK_PASSWORD_PROMPT=time_hex xsecurelock 使用Polybar
polybar_run &

# 打开中文输入法
fcitx5 &

# 设置键盘灵敏度
xset r rate 300 45

# feh配置桌面
/home/rqdmap/.fehbg

# 配置Miku Cursor
xsetroot -cursor_name left_ptr

# 设置屏幕待机时间为30分钟(好像没用)
xset dpms 1800 1800 1800

# 打开词典
if [[ -e `pidof goldendict` ]]; then
	goldendict &
fi

# 打开unclutter(隐藏非活跃鼠标)
unclutter -b 


pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         3
bspc config focused_border_color "#3F73B6"

bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a explorer.exe state=pseudo_tiled

