#! /bin/bash

# 多显示屏配置
name1="eDP-1-1"
rate1="165.01"
mode1="1920x1080"

name2="HDMI-0"
mode2="2560x1080"
rate2="74.99"


both="0"

# Home AOC
# mode="1920x1080"
# rate="60"

function setMonitor(){
	xrandr --output $1 --rate $2 --mode $3
	if [[ -n $4 ]]; then bspc monitor $1 -d -
	else bspc monitor $1 -d I II III IV V VI VII VII IX X
	fi
}

function clearMonitor(){
	xrandr --output $1 --off
	bspc monitor $1 -r
}


if [ "$(xrandr | grep " connected " | grep $name2)" ]; then
	setMonitor $name2 $rate2 $mode2

	if [ $both == '0' ]; then
		clearMonitor $name1
	else	
		setMonitor $name1 $rate1 $mode1 'one'
		xrandr --output $name2 --primary --output $name1 --left-of $name2
		bspc wm --reorder-monitors $name2 $name1
	fi
else
	setMonitor $name1 $rate1 $mode1
	clearMonitor $name2
fi

# Execute a binary executable, restart it if it is running
function cleverStart() {
    if pgrep $1 > /dev/null ; then pkill $1; fi
	nohup $1 $2 >> $HOME/.log/$1.log 2>&1 &
}


#in/env XSECURELOCK_PASSWORD_PROMPT=time_hex xsecurelock 使用Polybar
cleverStart polybar_run 

# 打开中文输入法
cleverStart fcitx5

# 设置键盘灵敏度
xset r rate 300 45

# feh配置桌面
/home/rqdmap/.fehbg

# 配置Miku Cursor
xsetroot -cursor_name left_ptr

# 设置屏幕待机时间为30分钟(好像没用)
xset dpms 1800 1800 1800

# 打开词典
cleverStart goldendict

# 打开unclutter(隐藏非活跃鼠标)
cleverStart unclutter -b

cleverStart aw-server-rust
cleverStart aw-watcher-afk
cleverStart aw-watcher-window

cleverStart sxhkd

bspc config border_width         3
bspc config focused_border_color "#3F73B6"
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled

