#!/bin/bash

pkill -x polybar > /dev/null 2>&1

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
	MONITOR=$m polybar top > /dev/null 2>&1 &
	MONITOR=$m polybar bottom > /dev/null 2>&1 &
done

# polybar 重启后正确显示层级关机: https://github.com/polybar/polybar/issues/2972
sleep 1
xdo lower -N "Polybar"
