#!/bin/bash

both="0"
# 多显示屏配置
name1=$(xrandr | grep -i edp | grep -w connected  | cut -d ' ' -f 1)
rate1="165.01"
mode1="1920x1080"

name2=$(xrandr | grep -i hdmi | grep -w connected  | cut -d ' ' -f 1)
mode2="2560x1080"
rate2="74.99"

# # Home AOC
# mode2="1920x1080"
# rate2="144"

function setMonitor(){
	xrandr --output $1 --rate $2 --mode $3
	if [[ -n $4 ]]; then
        bspc monitor $1 -d -
	else
        bspc monitor $1 -d I II III IV V VI VII VII IX X
	fi
}

function clearMonitor(){
	xrandr --output $1 --off
	bspc monitor $1 -r
}

if [ "$name2" ]; then
	setMonitor $name2 $rate2 $mode2

	if [ $both == '0' ]; then
		clearMonitor $name1
	else
		setMonitor $name1 $rate1 $mode1 'one'
		xrandr --output $name2 --primary --output $name1 --left-of $name2
		bspc wm --reorder-monitors $name2 $name1
	fi
else
	setMonitor $name1 $rate1 $mode1
	clearMonitor $name2
fi

# Execute a binary executable, restart it if it is running
# 存在BUG: 无法终止子进程; $1的格式无法保证为单一的命令, 可能包含路径
function foo() {
    sudo_flag=""
    if [ $1 = "sudo" ]; then
        sudo_flag="sudo"
        shift
    fi

    for pid in $(pgrep -f $1); do
        pkill -TERM -P $pid
        kill -TERM $pid
    done
    nohup $sudo_flag $1 ${@:2} >> $HOME/.log/$(basename $1).log 2>&1 &
}


PATH="$HOME/.local/bin:$PATH"
foo polybar_run 

# 打开中文输入法
foo fcitx5

# 设置键盘灵敏度
xset r rate 300 45

# feh配置桌面
/home/rqdmap/.fehbg

# 配置Miku Cursor
xsetroot -cursor_name left_ptr

# 禁止屏幕休眠
xset dpms 0 0 0

# 启用定时锁屏
# https://askubuntu.com/questions/509507/please-explain-the-parameters-noexpose-and-cycle-in-xset
# xset s <timeout> <cycle>:
#	After idle for <timeout> seconds, activate dimmer.
#	After <cycle> seconds, activate xsecurelock.
xset s on
xset s 120 60
foo xss-lock "-n /usr/lib/xsecurelock/dimmer -l -- xsecurelock"

# 打开词典
foo goldendict

# 打开unclutter(隐藏非活跃鼠标)
foo unclutter -b

foo aw-server-rust
foo aw-watcher-afk
foo aw-watcher-window

# foo wired
foo dunst

foo picom

foo clash

foo sxhkd

foo /data/rqdmap/Applications/frp/frps.sh

foo sudo /data/rqdmap/Applications/frp/auto_proxy.sh

pushd ~/Documents/moneybook/
foo fava main.bean
popd

# foo syncthing

# # Swap Ctrl and CapsLock
# setxkbmap -option ctrl:swapcaps
# Make CapsLock an additional Ctrl
setxkbmap -option ctrl:nocaps

# 默认设置Speaker音量为100%, 通过Master整体调节音量
amixer -c 1 set Speaker 100 > /dev/null
amixer -c 1 set Master 50 > /dev/null

# #############
# BSPC Rules  #
# #############
bspc config border_width				3
bspc config focused_border_color	"#3F73B6"
# bspc config presel_feedback_color	"#76628A"
bspc config window_gap				10
bspc config split_ratio				0.52
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc rule -a "*:Figure:*" state=floating
bspc rule -a Tk state=floating
bspc rule -a Zathura state=tiled
bspc rule -a TelegramDesktop state=floating rectangle=1200x900+0+0 center=on
bspc rule -a vlc state=floating rectangle=1200x900+0+0 center=on
bspc rule -a "*:*:screenkey" layer=above
bspc rule -a wemeetapp state=floating center=on
bspc rule -a obs state=floating  center=on
bspc rule -a gnome-font-viewer state=floating center=on
bspc rule -a "Blueman-manager:blueman-manager:Bluetooth Devices" state=floating rectangle=1200x900+0+0 center=on
bspc rule -a "GParted" state=floating rectangle=1200x900+0+0 center=on
