use_trash = false
xdg_open = false
xdg_open_fork = false
watch_files = true

[display]
# default, hsplit
mode = "default"

automatically_count_files = true
collapse_preview = false
scroll_offset = 4
# ratios for parent view (optional), current view and preview
column_ratio = [1, 3, 3]
show_borders = true
show_hidden = false
show_icons = true
tilde_in_titlebar = true
# none, absolute, relative
line_number_style = "relative"

[display.sort]
# lexical, mtime, natural
sort_method = "mtime"
case_sensitive = true
directories_first = false
reverse = true

[preview]
max_preview_size = 2097152                           # 2MB
preview_script = "~/.config/joshuto/preview_file.sh" # make sure it's marked as executable
preview_shown_hook_script = "~/.config/joshuto/on_preview_shown"
preview_removed_hook_script = "~/.config/joshuto/on_preview_removed"

[tab]
# inherit, home, root
home_page = "home"
