font:
  normal:
    family: Iosevka Nerd Font
  bold:
    family: Iosevka Nerd Font
    style: Bold

  italic:
    family: Iosevka Nerd Font
    style: Italic

  bold_italic:
    family: Iosevka Nerd Font
    style: Bold Italic
  size: 13

cursor:
  style:
    shape: Block
    blinking: On
  blink_interval: 500
  blink_timeout: 0

# shell:
#   program: /bin/zsh
#   args:
#     - --login

mouse:
  hide_when_typing: true

window:
  padding:
   x: 20
   y: 20

scale_with_dpi: true


# Colors (Gruvbox dark)
colors:
  primary:
    # hard contrast background - '#1d2021'
    background:        &gruvbox_dark_bg '#282828'
    # soft contrast background - '#32302f'
    foreground:        '#ebdbb2'
    bright_foreground: '#fbf1c7'
    dim_foreground:    '#a89984'
  cursor:
    text:   CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text:   CellBackground
    cursor: CellForeground
  # search:
  #   matches:
  #     foreground: '#000000'
  #     background: '#ffffff'
  #   focused_match:
  #    foreground: CellBackground
  #    background: CellForeground
  #   bar:
  #     background: ''
  #     foreground: ''
  # line_indicator:
  #   foreground: None
  #   background: None
  selection:
    text:       CellBackground
    background: CellForeground
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
  normal:
    black:   *gruvbox_dark_bg
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'
  dim:
    black:   '#32302f'
    red:     '#9d0006'
    green:   '#79740e'
    yellow:  '#b57614'
    blue:    '#076678'
    magenta: '#8f3f71'
    cyan:    '#427b58'
    white:   '#928374'
  indexed_colors:
    - { index:  66, color: '#458588' }
    - { index:  72, color: '#689d6a' }
    - { index: 106, color: '#98971a' }
    - { index: 108, color: '#8ec07c' }
    - { index: 109, color: '#83a598' }
    - { index: 124, color: '#cc241d' }
    - { index: 132, color: '#b16286' }
    - { index: 142, color: '#b8bb26' }
    - { index: 166, color: '#d65d0e' }
    - { index: 167, color: '#fb4934' }
    - { index: 172, color: '#d79921' }
    - { index: 175, color: '#d3869b' }
    - { index: 208, color: '#fe8019' }
    - { index: 214, color: '#fabd2f' }
    - { index: 223, color: '#ebdbb2' }
    - { index: 229, color: '#fbf1c7' }
    - { index: 234, color: '#1d2021' }
    - { index: 235, color: '#282828' }
    - { index: 236, color: '#32302f' }
    - { index: 237, color: '#3c3836' }
    - { index: 239, color: '#504945' }
    - { index: 241, color: '#665c54' }
    - { index: 243, color: '#7c6f64' }
    - { index: 245, color: '#928374' }
    - { index: 246, color: '#a89984' }
    - { index: 248, color: '#bdae93' }
    - { index: 250, color: '#d5c4a1' }

key_bindings:
  - {key: Key1, mods: Control, action: ScrollLineUp}
  - {key: Key2, mods: Control, action: ScrollLineDown}
  # - { key: A,         mods: Alt,       chars: "\x1ba"                       }
  # - { key: B,         mods: Alt,       chars: "\x1bb"                       }
  # - { key: C,         mods: Alt,       chars: "\x1bc"                       }
  # - { key: D,         mods: Alt,       chars: "\x1bd"                       }
  # - { key: E,         mods: Alt,       chars: "\x1be"                       }
  # - { key: F,         mods: Alt,       chars: "\x1bf"                       }
  # - { key: G,         mods: Alt,       chars: "\x1bg"                       }
  # - { key: H,         mods: Alt,       chars: "\x1bh"                       }
  # - { key: I,         mods: Alt,       chars: "\x1bi"                       }
  # - { key: J,         mods: Alt,       chars: "\x1bj"                       }
  # - { key: K,         mods: Alt,       chars: "\x1bk"                       }
  # - { key: L,         mods: Alt,       chars: "\x1bl"                       }
  # - { key: M,         mods: Alt,       chars: "\x1bm"                       }
  # - { key: N,         mods: Alt,       chars: "\x1bn"                       }
  # - { key: O,         mods: Alt,       chars: "\x1bo"                       }
  # - { key: P,         mods: Alt,       chars: "\x1bp"                       }
  # - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
  # - { key: R,         mods: Alt,       chars: "\x1br"                       }
  # - { key: S,         mods: Alt,       chars: "\x1bs"                       }
  # - { key: T,         mods: Alt,       chars: "\x1bt"                       }
  # - { key: U,         mods: Alt,       chars: "\x1bu"                       }
  # - { key: V,         mods: Alt,       chars: "\x1bv"                       }
  # - { key: W,         mods: Alt,       chars: "\x1bw"                       }
  # - { key: X,         mods: Alt,       chars: "\x1bx"                       }
  # - { key: Y,         mods: Alt,       chars: "\x1by"                       }
  # - { key: Z,         mods: Alt,       chars: "\x1bz"                       }
  # - { key: A,         mods: Alt|Shift, chars: "\x1bA"                       }
  # - { key: B,         mods: Alt|Shift, chars: "\x1bB"                       }
  # - { key: C,         mods: Alt|Shift, chars: "\x1bC"                       }
  # - { key: D,         mods: Alt|Shift, chars: "\x1bD"                       }
  # - { key: E,         mods: Alt|Shift, chars: "\x1bE"                       }
  # - { key: F,         mods: Alt|Shift, chars: "\x1bF"                       }
  # - { key: G,         mods: Alt|Shift, chars: "\x1bG"                       }
  # - { key: H,         mods: Alt|Shift, chars: "\x1bH"                       }
  # - { key: I,         mods: Alt|Shift, chars: "\x1bI"                       }
  # - { key: J,         mods: Alt|Shift, chars: "\x1bJ"                       }
  # - { key: K,         mods: Alt|Shift, chars: "\x1bK"                       }
  # - { key: L,         mods: Alt|Shift, chars: "\x1bL"                       }
  # - { key: M,         mods: Alt|Shift, chars: "\x1bM"                       }
  # - { key: N,         mods: Alt|Shift, chars: "\x1bN"                       }
  # - { key: O,         mods: Alt|Shift, chars: "\x1bO"                       }
  # - { key: P,         mods: Alt|Shift, chars: "\x1bP"                       }
  # - { key: Q,         mods: Alt|Shift, chars: "\x1bQ"                       }
  # - { key: R,         mods: Alt|Shift, chars: "\x1bR"                       }
  # - { key: S,         mods: Alt|Shift, chars: "\x1bS"                       }
  # - { key: T,         mods: Alt|Shift, chars: "\x1bT"                       }
  # - { key: U,         mods: Alt|Shift, chars: "\x1bU"                       }
  # - { key: V,         mods: Alt|Shift, chars: "\x1bV"                       }
  # - { key: W,         mods: Alt|Shift, chars: "\x1bW"                       }
  # - { key: X,         mods: Alt|Shift, chars: "\x1bX"                       }
  # - { key: Y,         mods: Alt|Shift, chars: "\x1bY"                       }
  # - { key: Z,         mods: Alt|Shift, chars: "\x1bZ"                       }
  # - { key: Key1,      mods: Alt,       chars: "\x1b1"                       }
  # - { key: Key2,      mods: Alt,       chars: "\x1b2"                       }
  # - { key: Key3,      mods: Alt,       chars: "\x1b3"                       }
  # - { key: Key4,      mods: Alt,       chars: "\x1b4"                       }
  # - { key: Key5,      mods: Alt,       chars: "\x1b5"                       }
  # - { key: Key6,      mods: Alt,       chars: "\x1b6"                       }
  # - { key: Key7,      mods: Alt,       chars: "\x1b7"                       }
  # - { key: Key8,      mods: Alt,       chars: "\x1b8"                       }
  # - { key: Key9,      mods: Alt,       chars: "\x1b9"                       }
  # - { key: Key0,      mods: Alt,       chars: "\x1b0"                       }
  # - { key: Space,     mods: Control,   chars: "\x00"                        } # Ctrl + Space
  # - { key: Grave,     mods: Alt,       chars: "\x1b`"                       } # Alt + `
  # - { key: Grave,     mods: Alt|Shift, chars: "\x1b~"                       } # Alt + ~
  # - { key: Period,    mods: Alt,       chars: "\x1b."                       } # Alt + .
  # - { key: Key8,      mods: Alt|Shift, chars: "\x1b*"                       } # Alt + *
  # - { key: Key3,      mods: Alt|Shift, chars: "\x1b#"                       } # Alt + #
  # - { key: Period,    mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
  # - { key: Comma,     mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
  # - { key: Minus,     mods: Alt|Shift, chars: "\x1b_"                       } # Alt + _
  # - { key: Key5,      mods: Alt|Shift, chars: "\x1b%"                       } # Alt + %
  # - { key: Key6,      mods: Alt|Shift, chars: "\x1b^"                       } # Alt + ^
  # - { key: Backslash, mods: Alt,       chars: "\x1b\\"                      } # Alt + \
  # - { key: Backslash, mods: Alt|Shift, chars: "\x1b|"                       } # Alt + |
  #
