[colors.primary]
background = "#282828"
bright_foreground = "#fbf1c7"
dim_foreground = "#a89984"
foreground = "#ebdbb2"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.dim]
black = "#32302f"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#928374"
yellow = "#b57614"

# [colors.primary]
# background = "#001100"
# foreground = "#00bb00"
#
# [colors.normal]
# black= "#001100"
# red= "#007700"
# green= "#00bb00"
# yellow= "#007700"
# blue= "#009900"
# magenta= "#00bb00"
# cyan= "#005500"
# white= "#00bb00"
#
# [colors.bright]
# black= "#007700"
# red= "#007700"
# green= "#00bb00"
# yellow= "#007700"
# blue= "#009900"
# magenta= "#00bb00"
# cyan= "#005500"
# white= "#00ff00"


[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor.style]
shape = "Block"
blinking = "Off"

[font]
size = 13

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"


[keyboard]
bindings = [
  { chars = "\u001F", key = "Slash", mods = "Control" },
  { action = "ScrollLineUp", key = "Key1", mods = "Control" },
  { action = "ScrollLineDown", key = "Key2", mods = "Control" },
# Todo
]

[mouse]
hide_when_typing = true

[window.padding]
x = 20
y = 20
