
serverAddr = "{{ .Envs.ZGO_VPS_IP }}"
serverPort = {{ .Envs.ZGO_VPS_PORT }}
auth.token = "{{ .Envs.TOKEN }}"

[[proxies]]
name = "SSH"
type = "tcp"
localIp = "127.0.0.1"
localPort = 22
remotePort = {{ .Envs.REMOTE_PORT }}

transport.useEncryption = true
transport.useCompression = true

